Refactoring/header and tabs
Pepelats-Q/react-project-kitchen-frontend pull request #18
Opened 2022-09-05 15:18 UTC by Nadezhda-Yarovaya

1 - типизированы: LangSelect, AuthForm

2 - в Header использованы NavButton из UI 
(сам NavButton из UI не имел прописанного класса navbutton_active - добавлены стили для активного класса )
также в Header сделала загрузку картинку текущего профиля

3 - Табы в роуты превращены, соответствующие роуты добавлены
кнопки TABS - теперь NavButton (добавила в тип NavButton тип Tab с соотв. стилями)
из UI удалила TabButton
осталось доделать позже по функционалу: когда в своем профиле убираем сердечко, список пока не обновляется (надо сделать обновление списка)

4 - кнопки языков как из макета сделала (мне лично прошлый вариант больше нравится, без border)

2022-09-05 17:39 UTC, MaratAkhmetzanov requested changes
Есть несколько моментов, которые я бы поправил. 

Также стоит посмотреть вложенные роуты и у табов переключение между роутами делать только на уровне внутренностей, а не глобально менять роут. Сейчас при смене роута происходит перерисовка всей страницы, но можно менять только внутренности конкретного компонента. Так можно будет избавиться от дерганья при смене табов.

2022-09-05 17:39 UTC, MaratAkhmetzanov commented on src/components/ui-library/Buttons/NavButton/NavButton.module.scss
>      & svg > path {
Я стили делал исходя из макетов. Там у навигационных кнопок при наведении меняется фон на $color-white10 и падинги слева и справа 16px, а не 12. 
Думаю, что это стоит оставить.

2022-09-05 17:39 UTC, MaratAkhmetzanov commented on src/components/ui-library/Buttons/NavButton/NavButton.module.scss
> +}
Этот класс есть выше (57 строка). Там используется &_active, что разворачивается в .navigation_active.
Также использование important это костыли.

2022-09-05 17:39 UTC, MaratAkhmetzanov commented on src/components/ui-library/Buttons/NavButton/NavButton.jsx
> +    tab: styles.tab_active,
Я бы табы вынес в отдельный компонент, а не расширял этот. Хоть и табы с навигационными кнопоками схожие по функциональности, я бы их разделил. Был компонент TabButton. Лучше его изменить, с учетом того, что там уже есть стиль

2022-09-05 17:39 UTC, MaratAkhmetzanov commented on src/components/ui-library/Buttons/NavButton/NavButton.jsx
> +      {image && <img alt={children} className={clsx(styles.image, className)} src={image} />}
Можно попробовать картинку через пропс icon передавать, а не отдельный пропс создавать. Там всё равно передается jsx и размеры одинаковые.

2022-09-05 17:39 UTC, MaratAkhmetzanov commented on src/components/ui-library/Buttons/NavButton/NavButton.module.scss
> -    }
Это было нужно чтобы стили не переопределялись стандартными.

2022-09-05 17:39 UTC, MaratAkhmetzanov commented on src/components/LangSelect/LangSelect.tsx
>        >
Это же не текстовая кнопка, а обычная, но с другим стилем. 
Вот текстовая:
![image](https://user-images.githubusercontent.com/9134797/188495382-f200aa95-ec45-43d4-9de9-fb03e23ea252.png)
А вот обычная: 
![image](https://user-images.githubusercontent.com/9134797/188495428-7158c648-6f56-4ac6-8222-6a91b8b3e3d3.png)

Лучше добавить тип обычной кнопке, а не ломать текстовую.

2022-09-06 17:15 UTC, MaratAkhmetzanov commented on .eslintrc.js
> +    'import/no-cycle':'warn',
Лучше оставить стандартное значение. Бесконечные циклы импортов это не очень хорошая вещь.

2022-09-07 05:03 UTC, Nadezhda-Yarovaya commented
по изменениям на 07-09: 
- в NavButton JSX-то передавалось, но без пропсов, то есть просто <img/>
или <p></p> 
я добавила поддержку пропсов, но eslint стал ругаться на спред пропсов (самая краткая запись) 
добавила в исключения еслинта: 
react/jsx-props-no-spreading warn

теперь изображение в jsx разметке попадает в icon


- focus visible - вернула прежние значения (убирала не просто так, а появлялась обводка в неожиданных местах почему-то; сейчас все ок, перепроверила)

2022-09-08 22:07 UTC, MaratAkhmetzanov approved these changes
Наконец добрался до ревью. 
Хорошо сделано.

Мелочи:
1. Линтер ругается на то что используется спред оператор в NavButton. 
2. Линтер ругается на пропсы не в алфовитном порядке на странице UI.

2022-09-09 03:43 UTC, merged