Feature/validation and ts
Pepelats-Q/react-project-kitchen-frontend pull request #19
Opened 2022-09-12 10:59 UTC by Nadezhda-Yarovaya

-сделала валидацию всех форм, унифицировала их по компоненту AuthForm 

- типизировала все файлы, включая экшены редьюсеров (убрала AnyAction)
кроме middleware.js, agent.js - пока не получилось их на ts перевести. Может быть, у тебя получится? 

-удалила ненужные редьюсеры 

- мобильную версию сделала - на любой странице верстка не ломается 
управление меню сделала через useState, без использования редакса 

осталось: 
- дотипизировать файлы middleware.js, agent.js
- протестить мобильную версию - исправить возможные баги в верстке 
- исправить any в некоторых местах на реальные типы

2022-09-12 23:43 UTC, MaratAkhmetzanov requested changes
Масштабно. Очень хорошо сделано 👍
Добавил комментарии. В основном только предложения и вопросы, но есть и то что желательно поправить.

2022-09-12 23:43 UTC, MaratAkhmetzanov commented on src/utils/typesActions.ts
> +}
Типы экшенов я бы в сами файлы редьюсеров убрал. Не вижу необходимости выносить их в отдельный файл, а если в одном файле держать, то неудобство создается, что тут все типы и нужно разграничение.
А почему интерфейсы, а не типы?

2022-09-13 12:07 UTC, Nadezhda-Yarovaya commented
кроме изменений по списку комментариев еще это сделано: 
- теги при добавлении в editor: сделала перенос на другую строку, если тегов много

- в ArticlePreview - ограничиваю количество символов, чтобы не все описание статьи показывалось, если есть много текста 

- насчет обязательных полей - убрала звездочки, добавила onBlur в хук useFormValidation.
Изменила кнопку - теперь она не disabled - на нее можно нажать, но если обязательные поля не заполнены, то на сервер не пойдет запрос

-интерфейсы вместо типов использую - только для удобства, т.к. ими экшены редьюсеров типизирую (удобнее запомнить, что ими именно эти объекты типизированы) 

-чтобы показывался текст статьи с тегами я использовала dangerouslySetInnerHTML (это поле из формы TextArea с markdown-разметкой)
На него сейчас ругается линт (предупреждение). Предлагаю оставить пока так, но подумать, что еще можно сделать (так же, как думаем насчет спреда пропсов)

-типизацию ошибок с сервера -в редьюсере-  пока не осилила. Предлагаю пока оставить any, позже над этим поработаю.

2022-09-13 18:09 UTC, MaratAkhmetzanov approved these changes
Прошелся. Есть некоторые косяки с версткой и пару багов увидел, но можно мерджить. Я займусь правками

2022-09-13 18:23 UTC, merged