Main page
Pepelats-Q/react-project-kitchen-frontend pull request #8
Opened 2022-07-29 19:17 UTC by Resaw-git

### Что изменено

- Поменял стили главной страницы
- Весь затронутый функционал остался рабочим
- Удалил линтер т.к не смог его настроить
- Исправил баг с переходом на страницу профиля
- Удалил линтер т.к не смог его настроить
- Не использовал UI библиотеку, в дальнейшем нужно будет поменять
- Не добавил пагинацию
- Убрал автологин, т.к не смог обычно авторизоваться) 

Вроде всё, может что то пропустил, пишите в телегу по вопросам
P.S не работает редирект

2022-07-30 14:48 UTC, MaratAkhmetzanov requested changes
При подключенном линтере, проект не запускается. Много ошибок.

1. Верни линтер. Без него, вид кода ухудшается сильно и ошибки возможны.
2. В верстке есть недочеты, но это пока не трогаем.
3. Хорошо, что исправил баг с профилем.
4. Насчёт автологина обсуди с Надеждой, пожалуйста. Мне и так и так удобно.
5. По использованию библиотеки согласен, что пока рано использовать её.
6. А что за редирект не работает?

2022-07-30 14:48 UTC, MaratAkhmetzanov commented on src/components/ArticlePreview/ArticlePreview.js
> +  }
Вот эту функцию вообще не понял. Для чего она?

Тут пропущены точки с запятой, двойные кавычки вместо одинарных и ещё линтер ругается на else.

2022-07-30 14:48 UTC, MaratAkhmetzanov commented on src/components/ArticlePreview/ArticlePreview.js
>          </div>
1. Двойные кавычки, вместо одинарных.
2. Ширина строки больше 100.
3. Ненужная пустая строка перед дивом.

2022-07-30 14:48 UTC, MaratAkhmetzanov commented on src/components/ArticlePreview/ArticlePreview.js
>      </div>
Тут табуляция сломана. Сложнее будет по коду вложенность отслеживать.

2022-07-30 14:48 UTC, MaratAkhmetzanov commented on src/components/ArticlePreview/style.module.css
> +    float: right !important;
Считаю, что !important это зло. Точнее думаю, что это костыль в результате того, что где-то сверстано некорректно.

2022-07-30 14:48 UTC, MaratAkhmetzanov commented on src/components/Header/header.module.css
> +
Лишняя пустая строка. Далее тоже есть несколько.

2022-07-30 14:48 UTC, MaratAkhmetzanov commented on src/components/Pages/Home/Banner/Banner.js
> +    <div className={style.banner}>
Пустые строки и лишний return. Смысла писать return нет, так как нет другого кода. Нужно сразу после стрелочный функции писать то что возвращается. Это ошибки линтера.

2022-07-30 14:48 UTC, MaratAkhmetzanov commented on src/components/Pages/Home/MainView/MainView.js
> +          Ваши лента
Тут опечатка. Должно быть «Ваша лента».

2022-07-30 14:48 UTC, MaratAkhmetzanov commented on src/components/Pages/Home/MainView/MainView.js
>  const YourFeedTab = (props) => {
Не прописаны PropTypes.

2022-07-30 14:48 UTC, MaratAkhmetzanov commented on src/components/Pages/Home/MainView/MainView.js
> +import styles from './style.module.css'
Кажется, что тут какой-то бардак с компонентами получается, так как у нас отдельные компоненты внутри pages. Надо будет с этим в будущем разобраться. Пока так можно оставить.

2022-07-30 14:48 UTC, MaratAkhmetzanov commented on src/components/Pages/Home/index.js
>                    tags={this.props.tags}
Не прописаны proptypes.

2022-07-30 14:48 UTC, MaratAkhmetzanov commented on src/components/Profile/Profile.js
>    if (props.isUser) {
proptypes

2022-07-30 14:48 UTC, MaratAkhmetzanov commented on src/components/Profile/Profile.js
> +      </button>
Потом надо будет на базовые компопнеты поменять. Пока так 🤷‍♂️

2022-07-30 14:48 UTC, MaratAkhmetzanov commented on src/middleware.js
> -        console.log('RESULT', res);
Лучше пока не трогать middleware. Разве что сразу переписывать, но думаю пока рано.

2022-07-30 14:48 UTC, MaratAkhmetzanov commented on src/reducers/home.js
> +  tags: ["app", "web", "frontend", "react"]
Кавычки

2022-07-30 14:48 UTC, MaratAkhmetzanov commented on src/store.js
> +// import { createLogger } from 'redux-logger';
Почему логгер закомментировал? Так то полезная штука.

2022-07-31 01:12 UTC, Resaw-git commented on src/components/App/App.js
> -      }
Решили в итоге убрать автологин

2022-07-31 01:12 UTC, Resaw-git commented on src/components/App/App.js
> +      this.context.router.replace(nextProps.redirectTo);
без понятия) в оригинале он присутствует

2022-07-31 01:14 UTC, Resaw-git commented on src/components/ArticleList/style.module.css
> +    border-top: 1px solid #2F2F37;
В дальнейшем сделаем единую точку констант для стилей

2022-07-31 01:15 UTC, Resaw-git commented on src/components/Profile/Profile.js
>    if (props.isUser) {
Тут избавимся от пропсов, будем использовать Redux

2022-07-31 01:17 UTC, Resaw-git commented on src/middleware.js
> -        console.log('RESULT', res);
сонсоль логи для дебага, после себя все логи чистим

2022-07-31 01:18 UTC, Resaw-git commented on src/store.js
> +// import { createLogger } from 'redux-logger';
засоряет лог, используй расширение браузера Redux DevTools

2022-07-31 02:40 UTC, Resaw-git commented
Изменил описание README.md добавил ссылок и шпаргалку по PRETIER.md

2022-07-31 13:45 UTC, MaratAkhmetzanov requested changes
У меня проект не запускается из-за 2 ошибок:
1. Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.js': Cannot find module 'typescript'
2. Error: resolve-url-loader: error processing CSS

Надо поставить node-sass и typescript.

И ещё у тебя в файлах, которые правил, куча ворнингов от линтера.
![image](https://user-images.githubusercontent.com/9134797/182029308-194e4ed1-6125-41f4-9ce7-18d2034a5b61.png)

2022-07-31 13:45 UTC, MaratAkhmetzanov commented on .gitignore
> +/src/components/Pages/Home/Tags/.sass-cache/e483fa148d42aa3e641526c8962b031e6cef5631/tags.module.scssc
Лучше node-sass поставь. У меня проект не запускается. Выдает Error: resolve-url-loader: error processing CSS

2022-07-31 18:17 UTC, Resaw-git commented on src/components/ArticlePreview/ArticlePreview.js
> +const NOT_FAVORITED_CLASS = `${styles.btn} ${styles.btn_sm} ${styles.btn_outline_primary}`;
Ок, а эти классы будут удалены с заменой на компонент кнопки из библиотеки UI

2022-08-01 16:24 UTC, MaratAkhmetzanov approved these changes

2022-08-02 10:47 UTC, merged